name: 'Regex Merge'
description: 'Github Action for multiple branches merging'
author: Alter Lagos
inputs:
  accessToken:
    description: 'Github token. Usually secrets.GITHUB_TOKEN'
    required: true
  headBranch:
    description: 'Branch to merge'
    required: true
  branchRegex:
    description: 'Regex pattern for all branches to be updated'
    required: false
  notifyConflicts:
    description: 'Comments in related PR to branch, notifying about the merge conflict'
    required: false
    default: true
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: 'git-merge'
  color: 'orange'